### PR TITLE
Properly close file before next data opened

### PR DESCRIPTION
**Pull request by ksunden**
Not sure I'm fully happy with the implementation (at least the `copy_dump_file` stuff), but it does fix some issues we have been seeing...

Alternative suggestions welcome.

### CODE REVIEW

**Comment by untzag** [comment]
@ksunden why do we need a secondary cached version after scans are completed? Just in-case somebody else opens the data object externally?

**Comment by ddkohler** [comment]
Should we have tests for this?

**Comment by untzag** [comment]
@ddkohler unfortunately we don't have a testing framework for yaqc-cmds right now. It's not easy for mainly-graphical applications.

**Comment by untzag** [comment]
@ksunden @ddkohler other than my question above I'm happy with this implementation

**Comment by ksunden** [comment]
I'm not sure what you mean by "secondary cached version"

The copying is done not to have a second version, but because of the problem with copying into a parent, which is apparently separate from the problem with the consistency flags/closing. (I set out to solve them both, hoping they were related, but alas not actually)

All this is doing is automating applying the workaround we discovered.

**Comment by ksunden** [comment]
> Should we have tests for this?

yes... but as @untzag said, not a trivial task... I think the route to testability goes through wright-group/wright-fakes (i.e. an easy way to stand up a full system worth of daemons in a repeatable way that is usable both in CI and on a local machine)

I think I'll spend a bit of time filling out the fs system over there today (not too hard, but want to add in the opas and components thereof, and set limits on the delays/mono which is there already [currently everything is the default of 0-1, which is not super helpful, also units are missing, which causes some weird behavior])

Beyond that there are tools like https://pypi.org/project/pytest-qt/ which do allow tests of gui things, but haven't learned how to use them effectively.

I think a good first test would be an integration test that simply makes a queue runs two-three short scans (more than one to cover issues that may occur due to changeover between scans)

**Comment by untzag** [comment]
> The copying is done not to have a second version, but because of the problem with copying into a parent, which is apparently separate from the problem with the consistency flags/closing. (I set out to solve them both, hoping they were related, but alas not actually)

Wait, what? That's terrible. Can you at least leave a comment in the code explaining this?

**Comment by ksunden** [comment]
I agree that it is not ideal, which is why I solicited alternatives when I opened the PR...

I meant to add a comment last night, but apparently neglected to do so, I can add one...

Again, any suggestions are welcome, it is certainly a hack. I wish I had a better grasp on why it was segfaulting...

**Comment by ksunden** [comment]
actually... I've thought of a few things to try before we move forward here:

first, and easiest: since we are no longer using swmr, there is no reason to use `libver="latest"`... I wonder if it is a problem with copying newer spec attrs into an older spec file (the versions are complicated in hdf5land, as even with the same version of h5py, it may be built against different versions of hdf5 utils, and the default opening behavior is to be as compatible as possible by using an earlier spec)

Second: (if that doesn't fix it): try to make a minimal example using `create_data` directly, rather than doing a full scan, see if it occurs right off the bat or only after further data is filled in.

My current suspicion is that the first will fix it.

**Comment by untzag** [comment]
@ksunden that is a FANTASTIC point

**Comment by ksunden** [comment]
Yes indeed, it seems to fix the problem
Just need to delete the copy_dump_data func and then I'll push up

**Review by untzag — APPROVED** [review]
:clap:

**Pull request merged**
